include:
  - "deployment/templates/.ci-templates.yml"

stages:
  - build
  - deploy
  - post-deploy

backend-build-image-push-ecr:
  stage: build
  extends:
    - .backend-variables
    - .int-environment
    - .build-image-push-ecr
  only:
    - main

ml-build-image-push-ecr:
  extends:
    - .ml-backend-variables
    - .int-environment
    - .build-image-push-ecr
  stage: build
  only:
    - main

build-frontend:
  image: node:latest
  stage: build
  only:
    - main
    - devtest
  script:
    - cd ./frontend/
    - npm install
    - CI=false npm run-script build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour

backend-deploy:
  stage: deploy
  needs:
    - backend-build-image-push-ecr
  extends:
    - .backend-variables
    - .int-environment
    - .deploy
  only:
    - main

frontend-deploy:
  stage: deploy
  extends:
    - .frontend-variables
    - .int-environment
    - .deploy
  only:
    - main
    - devtest

deploy-frontend:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  stage: post-deploy
  only:
    - main
    - devtest
  before_script:
    - aws --version
  script:
    - aws s3 sync ./frontend/dist/ $AWS_S3_URL --delete

ml-backend-deploy:
  stage: deploy
  needs:
    - ml-build-image-push-ecr
  extends:
    - .ml-backend-variables
    - .int-environment
    - .deploy
  only:
    - main
