include: 
  - 'templates/.ci-templates.yml'

stages:
  - build-image-push-ecr
  # - test
  # - deploy

backend-build-image-push-ecr:
  stage: build-image-push-ecr
  extends:
    - .backend-variables
    - .build-image-push-ecr 
  only:
    - main
    - stonk-pix.backend-CFT-deploy

# ml-build-image:
#   extends:
#     - .ml-backend-variables
#     - .build-docker-push-ecr 
#   stage: build-image
