include: 
  - template: templates/.ci-templates.yml
  - template: AWS/Deploy-ECS.gitlab-ci.yml  

stages:
  - build-image
  # - test
  # - deploy
  
default:
  image: ruby:2.7.4

variables:
  var: value

backend-build-image:
  extends:
    - .backend-variables
    - .build-docker-push-ecr 
  stage: build-image
  only:
    - main
    - stonk-pix.backend-CFT-deploy

# ml-build-image:
#   extends:
#     - .ml-backend-variables
#     - .build-docker-push-ecr 
#   stage: build-image
