version: "3.7"

services:
  ml:
    image: python:3.9-buster
    command: sh -c "pip install -r requirements.txt && python3 ml_pipeline.py"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_URI: mongo
      DB_PASSWORD: example
      DB_USERNAME: root

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data: