version: "3.7"

services:
  ml:
    image: python:3.8-buster
    command: sh -c "pip install -r requirements.txt && python3 ml_pipeline.py"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGO_HOST: mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data: