AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates an Amazon CloudFront distribution to expose the stonkpix app
Parameters:
  BucketStackName:
    Description: Name of an active CloudFormation Stack that holds the S3 bucket and OAI  for the front end
    Type: String
    Default: stonk-pix-s3-int
    AllowedValues:
      - stonk-pix-s3-int
      - stonk-pix-s3-prod
  Environment:
    Type: String
    Default: int
    AllowedValues:
      - int
      - prod
  CertificateArn:
    Type: String
    Default: "arn:aws:acm:us-east-1:525599889582:certificate/daf4b95d-b11c-4a75-a943-4bb213d7ca1a"
Resources:
  CFDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases: ["stonkpix.net"]
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref CertificateArn
        Origins:
          - DomainName:
              Fn::Join:
                - ""
                - - "stonk-pix-frontend-"
                  - !Ref Environment
                  - ".s3.us-west-2.amazonaws.com"
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - "origin-access-identity/cloudfront/"
                    - Fn::ImportValue: !Sub "${BucketStackName}-OriginAccessIdentity"
        Enabled: "true"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: myS3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Logging:
          Bucket:
            Fn::Join:
              - ""
              - - "stonk-pix-frontend-logs-"
                - !Ref Environment
                - ".s3.us-west-2.amazonaws.com"
          Prefix: "cloudfront-access-logs"
