variables:
  IMAGE_REPOSITORY_URL: 525599889582.dkr.ecr.us-west-2.amazonaws.com
  DOCKER_HOST: tcp://docker:2375
  
.backend-variables:
  variables:
    APP_NAME: stonk-pix-backend
    DOCKER_DIRECTORY_PATH: backend

.ml-backend-variables:
  variables: 
    APP_NAME: stonk-pix-ml-backend
    DOCKER_DIRECTORY_PATH: ml_backend 

.frontend-variables:
  variables: 
    APP_NAME: stonk-pix-frontend
    DOCKER_DIRECTORY_PATH: frontend

  
.build-image-push-ecr:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $IMAGE_REPOSITORY_URL/$APP_NAME:$CI_PIPELINE_IID ./$DOCKER_DIRECTORY_PATH
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPOSITORY_URL
    - docker push $IMAGE_REPOSITORY_URL/$APP_NAME:$CI_PIPELINE_IID   
  interruptible: true     
  only:
    - main
    - stonk-pix.backend-CFT-deploy
