.backend-variables:
  variables:
    var: value
    CI_AWS_ECS_CLUSTER: backend-jams
    CI_AWS_ECS_SERVICE: sample-app-service
    CI_AWS_ECS_TASK_DEFINITION: first-run-task-definition:1  

.ml-backend-variables:
  variables: 
    var: value   
    CI_AWS_ECS_CLUSTER: backend-jams
    CI_AWS_ECS_SERVICE: sample-app-service
    CI_AWS_ECS_TASK_DEFINITION: first-run-task-definition:1  

.frontend-variables:
  variables: 
    var: value   
  
.build-docker-push-ecr:
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  interruptible: true     
  only:
    - main
    - stonk-pix.backend-CFT-deploy