variables:
  IMAGE_REPOSITORY_URL: 525599889582.dkr.ecr.us-west-2.amazonaws.com
  AWS_DEFAULT_REGION: us-west-2
  APP_NAME: stonk-pix-backend
  DOCKER_HOST: tcp://docker:2375
  
.backend-variables:
  variables:
    var: value
    CI_AWS_ECS_CLUSTER: backend-jams
    CI_AWS_ECS_SERVICE: sample-app-service
    CI_AWS_ECS_TASK_DEFINITION: first-run-task-definition:1

.ml-backend-variables:
  variables: 
    var: value   
    CI_AWS_ECS_CLUSTER: backend-jams
    CI_AWS_ECS_SERVICE: sample-app-service
    CI_AWS_ECS_TASK_DEFINITION: first-run-task-definition:1  

.frontend-variables:
  variables: 
    var: value   
  
.build-image-push-ecr:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID ./backend/Dockerfile
    - aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_REPOSITORY_URL
    - docker push $IMAGE_REPOSITORY_URL/$APP_NAME:$CI_PIPELINE_IID   
  interruptible: true     
  only:
    - main
    - stonk-pix.backend-CFT-deploy
